// PRECISÃO LISTA L1
export const PRESSIONEOATAQUE = 'PRESSIONEOATAQUE';
export const RITMOFATAL = 'RITMOFATAL';
export const AGILIDADENOSPES = 'AGILIDADENOSPES';
export const CONQUISTADOR = 'CONQUISTADOR';

// PRECISÃO LISTA L2
export const CURAEXCESSIVA = 'CURA EXCESSIVA';
export const TRIUNFO = 'TRIUNFO';
export const PRESENCADEESPIRITO = 'PRESENCADEESPIRITO';

// PRECISÃO LISTA L3
export const LENDAESPONTANEIDADE = 'LENDAESPONTANEIDADE';
export const LENDATENACIDADE = 'LENDATENACIDADE';
export const LENDALINHAGEM = 'LENDALINHAGEM ';

// PRECISÃO LISTA L4
export const GOLPEDEMISERICORDIA = 'GOLPEDEMISERICORDIA';
export const DILACERAR = 'DILACERAR';
export const ATEAMORTE = 'ATEAMORTE ';
